/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Nicolaslee
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jTextField51 = new javax.swing.JTextField();
        jTextField52 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        jTextField55 = new javax.swing.JTextField();
        jTextField56 = new javax.swing.JTextField();
        jTextField57 = new javax.swing.JTextField();
        jTextField58 = new javax.swing.JTextField();
        jTextField59 = new javax.swing.JTextField();
        jTextField60 = new javax.swing.JTextField();
        jTextField61 = new javax.swing.JTextField();
        jTextField62 = new javax.swing.JTextField();
        jTextField63 = new javax.swing.JTextField();
        jTextField64 = new javax.swing.JTextField();
        jTextField65 = new javax.swing.JTextField();
        jTextField66 = new javax.swing.JTextField();
        jTextField67 = new javax.swing.JTextField();
        jTextField68 = new javax.swing.JTextField();
        jTextField69 = new javax.swing.JTextField();
        jTextField70 = new javax.swing.JTextField();
        jTextField71 = new javax.swing.JTextField();
        jTextField72 = new javax.swing.JTextField();
        jTextField73 = new javax.swing.JTextField();
        jTextField74 = new javax.swing.JTextField();
        jTextField75 = new javax.swing.JTextField();
        jTextField76 = new javax.swing.JTextField();
        jTextField77 = new javax.swing.JTextField();
        jTextField78 = new javax.swing.JTextField();
        jTextField79 = new javax.swing.JTextField();
        jTextField80 = new javax.swing.JTextField();
        jTextField81 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout());

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1);

        jTextField2.setText("jTextField2");
        jPanel1.add(jTextField2);

        jTextField3.setText("jTextField3");
        jPanel1.add(jTextField3);

        jTextField4.setText("jTextField4");
        jPanel1.add(jTextField4);

        jTextField5.setText("jTextField5");
        jPanel1.add(jTextField5);

        jTextField6.setText("jTextField6");
        jPanel1.add(jTextField6);

        jTextField7.setText("jTextField7");
        jPanel1.add(jTextField7);

        jTextField8.setText("jTextField8");
        jPanel1.add(jTextField8);

        jTextField9.setText("jTextField9");
        jPanel1.add(jTextField9);

        jTextField10.setText("jTextField1");
        jPanel1.add(jTextField10);

        jTextField11.setText("jTextField2");
        jPanel1.add(jTextField11);

        jTextField12.setText("jTextField3");
        jPanel1.add(jTextField12);

        jTextField13.setText("jTextField4");
        jPanel1.add(jTextField13);

        jTextField14.setText("jTextField5");
        jPanel1.add(jTextField14);

        jTextField15.setText("jTextField6");
        jPanel1.add(jTextField15);

        jTextField16.setText("jTextField7");
        jPanel1.add(jTextField16);

        jTextField17.setText("jTextField8");
        jPanel1.add(jTextField17);

        jTextField18.setText("jTextField9");
        jPanel1.add(jTextField18);

        jTextField19.setText("jTextField1");
        jPanel1.add(jTextField19);

        jTextField20.setText("jTextField2");
        jPanel1.add(jTextField20);

        jTextField21.setText("jTextField3");
        jPanel1.add(jTextField21);

        jTextField22.setText("jTextField4");
        jPanel1.add(jTextField22);

        jTextField23.setText("jTextField5");
        jPanel1.add(jTextField23);

        jTextField24.setText("jTextField6");
        jPanel1.add(jTextField24);

        jTextField25.setText("jTextField7");
        jPanel1.add(jTextField25);

        jTextField26.setText("jTextField8");
        jPanel1.add(jTextField26);

        jTextField27.setText("jTextField9");
        jPanel1.add(jTextField27);

        jTextField28.setText("jTextField1");
        jPanel1.add(jTextField28);

        jTextField29.setText("jTextField2");
        jPanel1.add(jTextField29);

        jTextField30.setText("jTextField3");
        jPanel1.add(jTextField30);

        jTextField31.setText("jTextField4");
        jPanel1.add(jTextField31);

        jTextField32.setText("jTextField5");
        jPanel1.add(jTextField32);

        jTextField33.setText("jTextField6");
        jPanel1.add(jTextField33);

        jTextField34.setText("jTextField7");
        jPanel1.add(jTextField34);

        jTextField35.setText("jTextField8");
        jPanel1.add(jTextField35);

        jTextField36.setText("jTextField9");
        jPanel1.add(jTextField36);

        jTextField37.setText("jTextField1");
        jPanel1.add(jTextField37);

        jTextField38.setText("jTextField2");
        jPanel1.add(jTextField38);

        jTextField39.setText("jTextField3");
        jPanel1.add(jTextField39);

        jTextField40.setText("jTextField4");
        jPanel1.add(jTextField40);

        jTextField41.setText("jTextField5");
        jPanel1.add(jTextField41);

        jTextField42.setText("jTextField6");
        jPanel1.add(jTextField42);

        jTextField43.setText("jTextField7");
        jPanel1.add(jTextField43);

        jTextField44.setText("jTextField8");
        jPanel1.add(jTextField44);

        jTextField45.setText("jTextField9");
        jPanel1.add(jTextField45);

        jTextField46.setText("jTextField1");
        jPanel1.add(jTextField46);

        jTextField47.setText("jTextField2");
        jPanel1.add(jTextField47);

        jTextField48.setText("jTextField3");
        jPanel1.add(jTextField48);

        jTextField49.setText("jTextField4");
        jPanel1.add(jTextField49);

        jTextField50.setText("jTextField5");
        jPanel1.add(jTextField50);

        jTextField51.setText("jTextField6");
        jPanel1.add(jTextField51);

        jTextField52.setText("jTextField7");
        jPanel1.add(jTextField52);

        jTextField53.setText("jTextField8");
        jPanel1.add(jTextField53);

        jTextField54.setText("jTextField9");
        jPanel1.add(jTextField54);

        jTextField55.setText("jTextField1");
        jPanel1.add(jTextField55);

        jTextField56.setText("jTextField2");
        jPanel1.add(jTextField56);

        jTextField57.setText("jTextField3");
        jPanel1.add(jTextField57);

        jTextField58.setText("jTextField4");
        jPanel1.add(jTextField58);

        jTextField59.setText("jTextField5");
        jPanel1.add(jTextField59);

        jTextField60.setText("jTextField6");
        jPanel1.add(jTextField60);

        jTextField61.setText("jTextField7");
        jPanel1.add(jTextField61);

        jTextField62.setText("jTextField8");
        jPanel1.add(jTextField62);

        jTextField63.setText("jTextField9");
        jPanel1.add(jTextField63);

        jTextField64.setText("jTextField1");
        jPanel1.add(jTextField64);

        jTextField65.setText("jTextField2");
        jPanel1.add(jTextField65);

        jTextField66.setText("jTextField3");
        jPanel1.add(jTextField66);

        jTextField67.setText("jTextField4");
        jPanel1.add(jTextField67);

        jTextField68.setText("jTextField5");
        jPanel1.add(jTextField68);

        jTextField69.setText("jTextField6");
        jPanel1.add(jTextField69);

        jTextField70.setText("jTextField7");
        jPanel1.add(jTextField70);

        jTextField71.setText("jTextField8");
        jPanel1.add(jTextField71);

        jTextField72.setText("jTextField9");
        jPanel1.add(jTextField72);

        jTextField73.setText("jTextField1");
        jPanel1.add(jTextField73);

        jTextField74.setText("jTextField2");
        jPanel1.add(jTextField74);

        jTextField75.setText("jTextField3");
        jPanel1.add(jTextField75);

        jTextField76.setText("jTextField4");
        jPanel1.add(jTextField76);

        jTextField77.setText("jTextField5");
        jPanel1.add(jTextField77);

        jTextField78.setText("jTextField6");
        jPanel1.add(jTextField78);

        jTextField79.setText("jTextField7");
        jPanel1.add(jTextField79);

        jTextField80.setText("jTextField8");
        jPanel1.add(jTextField80);

        jTextField81.setText("jTextField9");
        jPanel1.add(jTextField81);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 5184, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField59;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextField62;
    private javax.swing.JTextField jTextField63;
    private javax.swing.JTextField jTextField64;
    private javax.swing.JTextField jTextField65;
    private javax.swing.JTextField jTextField66;
    private javax.swing.JTextField jTextField67;
    private javax.swing.JTextField jTextField68;
    private javax.swing.JTextField jTextField69;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField70;
    private javax.swing.JTextField jTextField71;
    private javax.swing.JTextField jTextField72;
    private javax.swing.JTextField jTextField73;
    private javax.swing.JTextField jTextField74;
    private javax.swing.JTextField jTextField75;
    private javax.swing.JTextField jTextField76;
    private javax.swing.JTextField jTextField77;
    private javax.swing.JTextField jTextField78;
    private javax.swing.JTextField jTextField79;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField80;
    private javax.swing.JTextField jTextField81;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
